INSERT INTO tb_location (name,x,y) VALUES ('MacDonalds',27,12)
INSERT INTO tb_location (name,x,y) VALUES ('BurgerKIng',31,18)
INSERT INTO tb_location (name,x,y) VALUES ('Starbucks',15,12)
INSERT INTO tb_location (name,x,y) VALUES ('Itau',19,21)
INSERT INTO tb_location (name,x,y) VALUES ('Central Park',12,8)
INSERT INTO tb_location (name,x,y) VALUES ('Bus station',23,6)
INSERT INTO tb_location (name,x,y) VALUES ('Bakery',28,2)